// this test code was generated by chatgpt using the starter code
#include <iostream>
#include "MultiSet.h"

int main() {
    // Create a MultiSet instance
    MultiSet ms1;
    MultiSet ms2;

    // Test inserting elements into ms1
    std::cout << "Inserting elements into ms1...\n";
    ms1.insert("A", 3);
    ms1.insert("B", 2);
    ms1.insert("C", 5);


    // Test inserting elements into ms2
    std::cout << "Inserting elements into ms2...\n";
    ms2.insert("B", 1);
    ms2.insert("D", 4);
    ms2.insert("A", 2);

    // Print ms1 and ms2
    std::cout << "ms1: " << ms1 << std::endl;
    std::cout << "ms2: " << ms2 << std::endl;

    // Test contains and count
    std::cout << "ms1 contains 'A': " << ms1.contains("A") << std::endl; // true
    std::cout << "ms1 contains 'D': " << ms1.contains("D") << std::endl;
    std::cout << "ms1 count of 'B': " << ms1.count("B") << std::endl; //
    std::cout << "ms2 count of 'C': " << ms2.count("C") << std::endl; //

    // Test removing elements
    std::cout << "Removing 2 'A' from ms1...\n";
    ms1.remove("A", 2);
    std::cout << "ms1 after removal: " << ms1 << std::endl;
    std::cout << "ms1 count of 'A': " << ms1.count("A") << std::endl;

    std::cout << "Removing 'B' from ms1...\n";
    ms1.remove("B", 2);
    std::cout << "ms1 after removal: " << ms1 << std::endl;
    std::cout << "ms1 count of 'B': " << ms1.count("B") << std::endl;

    // Refiling ms1 and ms2
    ms1.clear();
    ms2.clear();
    ms1.insert("A", 3);
    ms1.insert("B", 2);
    ms1.insert("C", 5);
    ms2.insert("B", 1);
    ms2.insert("D", 4);
    ms2.insert("A", 2);

    // Test remove arbitrary elements
    std::cout << "Removing 2 arbitrary elements from ms1...\n";
    auto removed = ms1.remove(2);
    std::cout << "Removed elements from ms2: ";
    for (const auto& elem : removed) {
        std::cout << elem << " ";
    }
    std::cout << "\n";

    // Refiling ms1 and ms2
    ms1.clear();
    ms2.clear();
    ms1.insert("A", 3);
    ms1.insert("B", 2);
    ms1.insert("C", 5);
    ms2.insert("B", 1);
    ms2.insert("D", 4);
    ms2.insert("A", 2);

    std::cout << "ms1: " << ms1 << std::endl;
    std::cout << "ms2: " << ms2 << std::endl;

    // Test union
    std::cout << "Union of ms1 and ms2: " << ms1.unionWith(ms2) <<  std::endl;

    // Test intersection
    std::cout << "Intersection of ms1 and ms2: " << ms1.intersectionWith(ms2) << std::endl;

    // Test difference
    //std::cout << "Difference between ms1 and ms2: " << ms1.differenceWith(ms2) << std::endl;

    // Test symmetric difference
    //std::cout << "Symmetric difference between ms1 and ms2: " << ms1.symmetricDifferenceWith(ms2) << std::endl;

    // Test unique keys
    std::cout << "Unique keys in ms2: ";
    for (const auto& key : ms2.uniqueKeys()) {
        std::cout << key << " ";
    }
    std::cout << std::endl;

    // Test clearing the MultiSet
    std::cout << "Clearing ms1...\n";
    ms1.clear();
    std::cout << "ms1 after clearing: " << ms1 << std::endl;

    return 0;
}

